[mypy]
python_version = 3.12
strict = false
warn_return_any = true
no_implicit_optional = true
ignore_missing_imports = true

[mypy-plotly.*]
ignore_missing_imports = true

[mypy-yfinance.*]
ignore_missing_imports = true

[mypy-psycopg_pool.*]
ignore_missing_imports = true

[mypy-requests.*]
ignore_missing_imports = true
